const color_map = new Map();
color_map.set("r", "Red");
color_map.set("b", "Blue");
color_map.set("g", "Green");
color_map.set("y", "Yellow");
color_map.set("m", "Magenta");
color_map.set("p", "Pink");
color_map.set("o", "Orange");
color_map.set("s", "Silver");
exports.color_map = color_map;
const color_keys = [];
const color_values = [];
for (const value of color_map.keys()) {
	color_keys.push(value);
}
for (const value of color_map.values()) {
	color_values.push(value);
}
exports.color_keys = color_keys;
exports.color_values = color_values;
const icon_map = new Map();
const emoji_map = new Map();
emoji_map.set("r", "🍎");
emoji_map.set("b", "🫐");
emoji_map.set("g", "🥑");
emoji_map.set("y", "🍋");
emoji_map.set("m", "🍇");
emoji_map.set("p", "🍑");
emoji_map.set("o", "🍊");
emoji_map.set("s", "🧄");
const special_emoji_map = new Map();
special_emoji_map.set("r", "🍓");
special_emoji_map.set("b", "🐟");
special_emoji_map.set("g", "🥦");
special_emoji_map.set("y", "🍍");
special_emoji_map.set("m", "🍆");
special_emoji_map.set("p", "🎂");
special_emoji_map.set("o", "🥕");
special_emoji_map.set("s", "🥛");
exports.special_emoji_map = special_emoji_map;
exports.emoji_map = emoji_map;
icon_map.set("sk", "Skip");
icon_map.set("+2", "Draw 2");
icon_map.set("re", "Reverse");
icon_map.set("fl", "Flip");
icon_map.set("-c", "Discard Color");
icon_map.set("th", "Trade Hands");
icon_map.set("se", "Skip Everyone");
icon_map.set("-rc", "Repeat Color Discard");
icon_map.set("wn", "Wild Number");
icon_map.set("sl", "Slap");
icon_map.set("ja", "Jackpot");
icon_map.set("pt", "Point Taken");
icon_map.set("+4", "Draw 4");
icon_map.set("rc", "Recycle");
icon_map.set("wa", "Warp");
icon_map.set("dp", "Double Play");
icon_map.set("sc", "Surprise Command");
icon_map.set("g2t", "Grab 2 Towers");
icon_map.set("sh", "Shift Hands");
icon_map.set("ra", "All Rotate");
icon_map.set("r10", "Rotate to 10");
icon_map.set("r2", "Rotate 2");
icon_map.set("da", "Dancing");
icon_map.set("+c", "Draw Color");
icon_map.set("cl", "Clear");
icon_map.set("gi", "Giveaway");
icon_map.set("pyt", "Pass Your Turn");
icon_map.set("dos", "Dos");
icon_map.set("ib", "Item Box");
icon_map.set("kfc", "Kevin's Famous Chili");
icon_map.set("ti", "Tilt");
icon_map.set("apf", "All Power Flip");
icon_map.set("t+2", "Targeted Draw 2");
icon_map.set("a+2", "All Draw 2");
icon_map.set("t+4", "Targeted Draw 4");
icon_map.set("ss", "Superstar");
icon_map.set("sk2", "Skip 2");
icon_map.set("gc", "Game Changer");
icon_map.set("pu", "Pileup");
icon_map.set("dt", "Drawn Together");
icon_map.set("pl2", "Play Two");
icon_map.set("a+1", "All Draw 1");
icon_map.set("cr", "Creeper");
icon_map.set("st", "Snorlax Traffic");
icon_map.set("bb", "Battle Bond");
icon_map.set("ho", "Howler");
icon_map.set("in", "Invisibility");
icon_map.set("sfh", "Shuffle Hands");
icon_map.set("hu", "Hurry Up!");
icon_map.set("sd", "Showdown");
icon_map.set("dp2", "Downpour 2");
icon_map.set("cru", "Creeperific Urrrgg");
icon_map.set("udg", "Uno Dice Game");
icon_map.set("clr", "Color Roulette");
icon_map.set("+6", "Draw 6");
icon_map.set("+10", "Draw 10");
icon_map.set("wp", "Whirlpool");
icon_map.set("ch", "Challenge");
icon_map.set("ditd", "Dip Into the Deck");
icon_map.set("sas", "Steal a Slice");
icon_map.set("eh", "Extreme Hit");
icon_map.set("h4", "Hit 4");
icon_map.set("mb", "Mambo");
icon_map.set("cts", "Crossing the Streams");
icon_map.set("wdt", "We Don't Talk");
icon_map.set("aa", "Altimeter Alert");
icon_map.set("cc", "Cosmic Crush");
icon_map.set("sam", "Special Agent Mater");
icon_map.set("ors", "Owen's Raper Squad");
icon_map.set("tf", "The Force");
icon_map.set("col", "Circle of Life");
icon_map.set("ig", "Infinity Gauntlet");
icon_map.set("cu", "Crash Up");
icon_map.set("scsl", "Screen Slayer");
icon_map.set("tdm", "Tiny Diamond's Mixtape");
icon_map.set("dk", "Duke Kaboom");
icon_map.set("fon", "Forces of Nature");
icon_map.set("bl", "Blind");
icon_map.set("kb", "Kickin' Battle");
icon_map.set("ks", "Kryptonite Symbol");
icon_map.set("dmtnt", "Dead Men Tell No Tales");
icon_map.set("de", "Dead End");
icon_map.set("+3", "Draw 3");
icon_map.set("+5", "Draw 5");
icon_map.set("+7", "Draw 7");
icon_map.set("+8", "Draw 8");
icon_map.set("+9", "Draw 9");
icon_map.set("fau", "Face Up");
icon_map.set("+4d4", "Draw 4 Discard 4");
icon_map.set("seu", "Shuffle Em Up");
icon_map.set("ep", "Exclusive Popcorn");
icon_map.set("run", "Run");
icon_map.set("ub", "Uno Bingo");
icon_map.set("ap2", "All Pass 2");
icon_map.set("p4", "Play 4");
icon_map.set("rr", "Reroll");
icon_map.set("gat", "Grab A Tower");
icon_map.set("rf", "Reflex");
icon_map.set("md", "Meltdown");
exports.icon_map = icon_map;

const icon_keys = [];
const icon_values = [];
for (const value of icon_map.keys()) {
	icon_keys.push(value);
}
for (const value of icon_map.values()) {
	icon_values.push(value);
}
for (let value = 0; value <= 23; value++) {
	icon_keys.push(value.toString());
}
icon_keys.push("-10");
exports.icon_keys = icon_keys;
exports.icon_values = icon_values;
console.log(icon_values);
